### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by korolr** [enjade-project/enjade#1]
this invite link is broken or has expired

**Comment by ubunturox104** [comment]
Issue has been fixed with new permanent link

**Comment by elsiete** [comment]
I still can't join the telegram group with this link : https://t.me/enjadeproject

**Comment by ubunturox104** [comment]
@elsiete Sorry to hear that. Do you want me to manually add you in? If so, state your username for Telegram.

**Comment by elsiete** [comment]
@ubunturox104 yeah, thanks.
Telegram username : @Elsiete7Moon

**Comment by ubunturox104** [comment]
Hi,

You need to change your privacy settings in order to continue.
